### ISSUE TITLE
Are sessions secure?

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/nbrsessionproxy#1]

**Comment by yuvipanda** [comment]
Assuming this is talking about securing access to rstudio, I'm guessing it is secured with @web.authenticated now. However, if you are using this in a non-containerized environment then other users on the machine can access your rstudio easily...

**Comment by yuvipanda** [comment]
Let's add documentation on this. TLDR is: 

1. Anyone who can reach the RStudio port can access RStudio
2. This means it is secure when running inside containers / other spawners that prevent access to localhost from other users. It's *insecure* otherwise.
3. Recommend people only run this with KubeSpawner & DockerSpawner.

**Comment by ryanlovett** [comment]
Documented by https://github.com/jupyterhub/nbrsessionproxy/commit/482fadc84b477e7b0c5fc50295308c202e4331c7#diff-04c6e90faac2675aa89e2176d2eec7d8.
